apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: QzNVOXZ2aE9SZDljWFZUOVlkcVo=
  AWS_SECRET_ACCESS_KEY: SHhVZElURVh4czc3YW1ONGJ0cVVIRTJubTdOa3g1UzhXNStqeEphRg==
kind: Secret
metadata:
  finalizers:
  - objectbucket.io/finalizer
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:AWS_ACCESS_KEY_ID: {}
        f:AWS_SECRET_ACCESS_KEY: {}
      f:metadata:
        f:finalizers:
          .: {}
          v:"objectbucket.io/finalizer": {}
        f:labels:
          .: {}
          f:app: {}
          f:bucket-provisioner: {}
          f:noobaa-domain: {}
        f:ownerReferences:
          .: {}
      f:type: {}
    manager: noobaa-operator
    operation: Update
    time: "2025-10-14T08:35:38Z"
  name: ai-rag-models
  namespace: keda
  ownerReferences:
  - apiVersion: objectbucket.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ObjectBucketClaim
    name: ai-rag-models
type: Opaque
